check

diff --git a/.github/workflows/htttp-check-pipeline.yml b/.github/workflows/htttp-check-pipeline.yml
--- a/.github/workflows/htttp-check-pipeline.yml
+++ b/.github/workflows/htttp-check-pipeline.yml
@@ -27,5 +27,9 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Curl
         run: |
-          curl -I https://www.google.com
-          echo "Curl done"
+          response = $(curl -I https://www.google.com)
+          if [ response -eq 200 ]; then
+            echo "Success"
+          else
+            echo "Failed"
+            exit 1
